export interface ElementData {
  number: number;
  symbol: string;
  name: string;
  weight: number;
  category: string;
  state: 'gas' | 'liquid' | 'solid';
  group: number;
  period: number;
  description: string;
  commonUses: string[];
  appearance: string;
}

export const COMMON_ELEMENTS: ElementData[] = [
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    weight: 1.008,
    category: 'nonmetal',
    state: 'gas',
    group: 1,
    period: 1,
    description: 'The lightest and most abundant element in the universe.',
    commonUses: ['Rocket fuel', 'Water production', 'Sun energy'],
    appearance: 'Colorless gas'
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    weight: 4.0026,
    category: 'noble gas',
    state: 'gas',
    group: 18,
    period: 1,
    description: 'A colorless, odorless, tasteless, non-toxic, inert, monatomic gas.',
    commonUses: ['Balloons', 'Cryogenics', 'Deep-sea diving'],
    appearance: 'Colorless gas'
  },
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    weight: 6.94,
    category: 'alkali metal',
    state: 'solid',
    group: 1,
    period: 2,
    description: 'The lightest metal and the lightest solid element.',
    commonUses: ['Batteries', 'Glass and ceramics', 'Mood-stabilizing drugs'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    weight: 12.011,
    category: 'nonmetal',
    state: 'solid',
    group: 14,
    period: 2,
    description: 'The basis of all known life on Earth.',
    commonUses: ['Diamonds', 'Graphite', 'Steel production'],
    appearance: 'Black (graphite) or Clear (diamond)'
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    weight: 14.007,
    category: 'nonmetal',
    state: 'gas',
    group: 15,
    period: 2,
    description: 'Makes up about 78% of Earth\'s atmosphere.',
    commonUses: ['Fertilizers', 'Food preservation', 'Liquid nitrogen cooling'],
    appearance: 'Colorless gas'
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    weight: 15.999,
    category: 'nonmetal',
    state: 'gas',
    group: 16,
    period: 2,
    description: 'Essential for respiration and combustion.',
    commonUses: ['Respiration', 'Steel manufacturing', 'Water'],
    appearance: 'Colorless gas'
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    weight: 18.998,
    category: 'halogen',
    state: 'gas',
    group: 17,
    period: 2,
    description: 'The most reactive element and the most electronegative.',
    commonUses: ['Toothpaste', 'Refrigerants', 'Teflon'],
    appearance: 'Pale yellow gas'
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    weight: 20.180,
    category: 'noble gas',
    state: 'gas',
    group: 18,
    period: 2,
    description: 'Known for its bright reddish-orange glow in discharge tubes.',
    commonUses: ['Neon signs', 'High-voltage indicators', 'Cryogenics'],
    appearance: 'Colorless gas'
  },
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    weight: 22.990,
    category: 'alkali metal',
    state: 'solid',
    group: 1,
    period: 3,
    description: 'A soft, silvery-white, highly reactive metal.',
    commonUses: ['Table salt', 'Street lights', 'Soap production'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    weight: 24.305,
    category: 'alkaline earth metal',
    state: 'solid',
    group: 2,
    period: 3,
    description: 'A shiny gray solid which bears a close physical resemblance to the other five alkaline earth metals.',
    commonUses: ['Flares', 'Lightweight alloys', 'Chlorophyll'],
    appearance: 'Shiny gray solid'
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminum',
    weight: 26.982,
    category: 'post-transition metal',
    state: 'solid',
    group: 13,
    period: 3,
    description: 'The most abundant metal in Earth\'s crust.',
    commonUses: ['Cans', 'Foil', 'Aircraft parts'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    weight: 28.085,
    category: 'metalloid',
    state: 'solid',
    group: 14,
    period: 3,
    description: 'A hard, brittle crystalline solid with a blue-grey metallic lustre.',
    commonUses: ['Computer chips', 'Glass', 'Solar cells'],
    appearance: 'Blue-grey metallic'
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    weight: 32.06,
    category: 'nonmetal',
    state: 'solid',
    group: 16,
    period: 3,
    description: 'A bright yellow, brittle solid at room temperature.',
    commonUses: ['Gunpowder', 'Matches', 'Sulfuric acid'],
    appearance: 'Yellow solid'
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    weight: 35.45,
    category: 'halogen',
    state: 'gas',
    group: 17,
    period: 3,
    description: 'A yellow-green gas that is a strong oxidizing agent.',
    commonUses: ['Swimming pools', 'Bleach', 'PVC plastic'],
    appearance: 'Pale green gas'
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    weight: 39.948,
    category: 'noble gas',
    state: 'gas',
    group: 18,
    period: 3,
    description: 'The third-most abundant gas in Earth\'s atmosphere.',
    commonUses: ['Light bulbs', 'Welding', 'Double-pane windows'],
    appearance: 'Colorless gas'
  },
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    weight: 39.098,
    category: 'alkali metal',
    state: 'solid',
    group: 1,
    period: 4,
    description: 'A silvery-white metal that is soft enough to be cut with a knife with little force.',
    commonUses: ['Fertilizers', 'Bananas', 'Soap'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    weight: 40.078,
    category: 'alkaline earth metal',
    state: 'solid',
    group: 2,
    period: 4,
    description: 'Essential for living organisms, particularly in cell physiology.',
    commonUses: ['Bones and teeth', 'Cement', 'Cheese making'],
    appearance: 'Dull gray metal'
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    weight: 55.845,
    category: 'transition metal',
    state: 'solid',
    group: 8,
    period: 4,
    description: 'The most common element on Earth by mass, forming much of Earth\'s outer and inner core.',
    commonUses: ['Steel', 'Construction', 'Hemoglobin'],
    appearance: 'Lustrous metallic gray'
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    weight: 58.693,
    category: 'transition metal',
    state: 'solid',
    group: 10,
    period: 4,
    description: 'A silvery-white lustrous metal with a slight golden tinge.',
    commonUses: ['Coins', 'Stainless steel', 'Rechargeable batteries'],
    appearance: 'Lustrous metallic'
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    weight: 63.546,
    category: 'transition metal',
    state: 'solid',
    group: 11,
    period: 4,
    description: 'A soft, malleable, and ductile metal with very high thermal and electrical conductivity.',
    commonUses: ['Electrical wiring', 'Plumbing', 'Statue of Liberty'],
    appearance: 'Red-orange metallic'
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    weight: 65.38,
    category: 'transition metal',
    state: 'solid',
    group: 12,
    period: 4,
    description: 'A slightly brittle metal at room temperature and has a blue-silvery appearance when oxidation is removed.',
    commonUses: ['Galvanizing steel', 'Sunscreen', 'Brass'],
    appearance: 'Silver-gray metallic'
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    weight: 107.87,
    category: 'transition metal',
    state: 'solid',
    group: 11,
    period: 5,
    description: 'A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.',
    commonUses: ['Jewelry', 'Photography', 'Mirrors'],
    appearance: 'Lustrous white metal'
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    weight: 118.71,
    category: 'post-transition metal',
    state: 'solid',
    group: 13,
    period: 5,
    description: 'A silvery-white metal with a faint yellow hue.',
    commonUses: ['Tin cans', 'Solder', 'Bronze'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    weight: 126.90,
    category: 'halogen',
    state: 'solid',
    group: 17,
    period: 5,
    description: 'A lustrous, purple-black non-metallic solid.',
    commonUses: ['Disinfectants', 'Thyroid health', 'Salt additive'],
    appearance: 'Purple-black solid'
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    weight: 195.08,
    category: 'transition metal',
    state: 'solid',
    group: 10,
    period: 6,
    description: 'A dense, malleable, ductile, highly unreactive, precious, silver-white transition metal.',
    commonUses: ['Catalytic converters', 'Jewelry', 'Laboratory equipment'],
    appearance: 'Silvery-white metal'
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    weight: 196.97,
    category: 'transition metal',
    state: 'solid',
    group: 11,
    period: 6,
    description: 'A bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.',
    commonUses: ['Jewelry', 'Investment', 'Electronics'],
    appearance: 'Yellow metallic'
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    weight: 200.59,
    category: 'transition metal',
    state: 'liquid',
    group: 12,
    period: 6,
    description: 'The only metallic element that is liquid at standard conditions for temperature and pressure.',
    commonUses: ['Thermometers', 'Barometers', 'Fluorescent lights'],
    appearance: 'Silvery liquid'
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    weight: 207.2,
    category: 'post-transition metal',
    state: 'solid',
    group: 14,
    period: 6,
    description: 'A heavy metal that is denser than most common materials.',
    commonUses: ['Batteries', 'Radiation shielding', 'Weights'],
    appearance: 'Dull gray metal'
  }
];
